name: example
description: A web app that uses AngularDart Components
# version: 0.0.``
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  angular: ^6.0.1
  angular_components: ^1.0.2
  ngutils:
    path: ../

dev_dependencies:
  angular_test: ^3.0.0
  build_runner: ^1.7.0
  build_test: ^1.3.1
  build_web_compilers: ^2.10.0
  meta: <1.7.0 # As of 07/12/2021, Dart throws errors if meta is 1.7.0 or above
  # pageloader: ^3.3.2
  pedantic: ^1.9.0
  test: ^1.16.5
