name: ngutils
description: A collection of services and components that helps you create beautiful and performant AngularDart websites easily.
version: 0.0.1
homepage: https://github.com/angulardart-community/ngutils

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies: 
  angular: ^6.0.1

dev_dependencies: 
  angular_test: ^3.0.0
  grinder: ^0.8.6
  test: ^1.16.5